### ISSUE TITLE
Feature request: Ignore yara rules by strings in rulename or tags

### ISSUE THREAD

**Issue by ruppde** [VirusTotal/yara-ci-issues#16]
Similar to the feature to ignore files it would be useful to ignore singe rules by rule name or tags to exclude rules which will trigger false positives because they're hunting rules and intentionally broad.

For example:
```yaml
rules:
  ignore:
  - "*hunting*"

ruletags:
  ignore:
  - "hunt"

```
