### ISSUE TITLE
FP not ignored as documented in docs

### ISSUE THREAD

**Issue by doomedraven** [VirusTotal/yara-ci-issues#2]
Hello guys, thanks for this feature, here is my config

```
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

files:
  accept:
  - "data/yara/**.yar"

false_positives:
  ignore:
    - rule: "CobaltStrikeBeacon"
```

And it always match the FP rule

https://github.com/kevoreilly/CAPEv2/runs/1538092106

any idea what could be wrong?

**Comment by plusvic** [comment]
The `.yara-ci.yml` file must be in your repository's root directory, but it's now in `.github/workflows`. Also notice that the following lines have no effect in the configuration:

```yaml
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
```

In fact we plan to implement better validation for the `.yara-ci.yml` file and these extra fields can cause an error in the future. So, your `.yara-ci.yml` file should look like:

```yaml
files:
  accept:
  - "data/yara/**.yar"

false_positives:
  ignore:
    - rule: "CobaltStrikeBeacon"
```
